### PR TITLE
fix: head hashing - support boolean properties

### LINKED ISSUE #2058: Error on hlx up with the express website
Run: 

```
git clone https://github.com/adobe/express-website
cd express-website
hlx up
```

The server does not start and you get error: `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type boolean (true)`

image

cli: v14.13.4
node: v14.18.2 or v16.17.0

Note that `hlx up` works for all other projects I have tested...

cc @tripodsan

### PR DESCRIPTION
**Pull request by kptdobe**
Fix #2058

### CODE REVIEW

File: src/server/HeadHtmlSupport.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ export default class HeadHtmlSupport {
           if (Array.isArray(v)) {
             v = JSON.stringify(v);
           }
-          h.update(v);
+          h.update(`${v}`);
```
Comment (tripodsan) [inline src/server/HeadHtmlSupport.js:39]:
```suggestion
          h.update(String(v));
```

**Review by tripodsan — APPROVED** [review]
