### PR TITLE
deploy may use the wrong git remote when adding a missing strain #514

### LINKED ISSUE #514: deploy may use the wrong git remote when adding a missing strain
**Description**
When running `npm test` on a git clone using `https://github.com/adobe/helix-cli.git`, the following error occurs:
```
1) hlx deploy (Integration)
       deploy reports affected strains with default proxy:

      AssertionError [ERR_ASSERTION]: '#\n# helix configuration for local development\n#\nversion: 1\n\ndefinitions:\n  defaults:\n    - &localRepo "http://localhost/ == '#\n# helix configuration for local development\n#\nversion: 1\n\ndefinitions:\n  defaults:\n    - &localRepo "http://localhost/
      + expected - actual

             address: 127.0.0.1

         new-strain:
           code: ssh://git@github.com/adobe/dummy.git#master
      -    content: https://github.com/adobe/helix-cli.git
      -    static: https://github.com/adobe/helix-cli.git/htdocs
      +    content: ssh://git@github.com/adobe/helix-cli.git
      +    static: ssh://git@github.com/adobe/helix-cli.git/htdocs
           package: 7b4d608e9eb05c0d0ca9222530b5cce408547c78

      at Context.it (test/testDeployCmd.js:273:12)
      at <anonymous>
```
The workaround is to create a fresh clone using the ssh URL `git@github.com:adobe/helix-cli.git`

**To Reproduce**
1. `git clone https://github.com/adobe/helix-cli.git`
2. `cd helix-cli`
3. `npm install && npm test`

**Expected behavior**
Tests shouldn't depend on which git clone method was used

**Version:**
0.13.3

### PR DESCRIPTION
**Pull request by rofe**
Fixes #514 

adjusted test so it converts potential https git URLs to ssh for comparison with expected result

### CODE REVIEW

**Comment by rofe** [comment]
> I think there is something wrong with the generation of the new strain.

I see. Actually I was wondering about that mix of repos, too... but I was expecting `--add` to use the git remote of the current checkout, so in this case, `helix-cli`.

**Comment by rofe** [comment]
I reverted the test fix, and made sure the correct working directory is being used for the creation of the default config. The generated strain has consistent git URLs across code, content and static now.

File: test/testDeployCmd.js [hunk 1]
```diff
@@ -267,7 +267,7 @@ describe('hlx deploy (Integration)', () => {
     assert.ok(log.indexOf('Affected strains of ssh://git@github.com/adobe/dummy.git#master') >= 0);
     assert.ok(log.indexOf('- new-strain') >= 0);
     await cmd.config.saveConfig(); // trigger manual save because of dry-run
-    const actual = await fs.readFile(cfg, 'utf-8');
+    const actual = (await fs.readFile(cfg, 'utf-8'));
```
Comment (tripodsan) [inline test/testDeployCmd.js]:
```suggestion
    const actual = await fs.readFile(cfg, 'utf-8');
```
