### PR TITLE
fix: don't respond when headers already sent

### LINKED ISSUE #2276: Simulator fails to serve pages with webm videos
```
error: Failed to proxy Franklin request /assets/header-animation-lets-talk.webm: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/Users/[redacted]/.nvm/versions/node/v16.19.1/lib/node_modules/@adobe/helix-cli/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/[redacted]/.nvm/versions/node/v16.19.1/lib/node_modules/@adobe/helix-cli/node_modules/express/lib/response.js:174:12)
    at HelixServer.handleProxyModeRequest (file:///Users/[redacted]/.nvm/versions/node/v16.19.1/lib/node_modules/@adobe/helix-cli/src/server/HelixServer.js:95:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #2276

### CODE REVIEW

File: src/server/HelixServer.js [hunk 1]
```diff
@@ -69,9 +79,13 @@ export class HelixServer extends BaseServer {
...
         liveReload.registerFile(ctx.requestId, filePath);
       }
+      log.debug(`${pfx}served local file ${filePath}`);
       return;
     } catch (e) {
-      log.debug(`Error while delivering resource ${ctx.path} - ${e.stack || e}`);
+      log.debug(`${pfx}unable to deliver local file ${ctx.path} - ${e.stack || e}`);
+      if (res.headersSent) {
+        return;
+      }
```
Comment (tripodsan) [inline src/server/HelixServer.js:88]: this is the actual fix: if serving a local file failed due to a communication error, the response was already initiated but it tried later to serve the proxied resource as well.

**Review by dominique-pfister — APPROVED** [review]
