### PR TITLE
fix(parcel): more robust handling of missing package.json

### LINKED ISSUE #881: hlx up: cannot read property 'devDependencies' of undefined
**Description**
I'm getting a `Cannot read property 'devDependencies' of undefined` after running hlx demo and hlx up from a empty folder.

**To Reproduce**

    export H=...full path of helix-cli/index.js
    mkdir empty-folder
    cd empty-folder
    $H demo xxx
    cd xxx
    $H up

which says:

    ....html.pre.js: Cannot read property 'devDependencies' of undefined
    at AdapterJSAsset.getPackage (...helix-cli/src/parcel/AdapterJSAsset.js:43:9)

**Version:**
at commit 0855c48

### PR DESCRIPTION
**Pull request by trieloff**
fixes #881

@bdelacretaz does this fix your issue?

### CODE REVIEW

**Comment by bdelacretaz** [comment]
It does fix it but it's not setting `pkg.devDependencies` anymore, dunno if that's required. 

I was just submitting my own fix, #883, I'll let you select the right one!

**Comment by trieloff** [comment]
I just noticed. Both a missing `package.json` and missing `devDependencies` would be an issue.

**Comment by bdelacretaz** [comment]
I think you need

    const pkg = await super.getPackage() || {}

or something like that in the current fix, as pkg itself might be null. It's still failing for me with that fix.

My fix at https://github.com/adobe/helix-cli/pull/883/files works (but maybe it's not the preferred style)

File: src/parcel/AdapterJSAsset.js [hunk 1]
```diff
@@ -39,9 +39,14 @@ class AdapterJSAsset extends JSAsset {
   }
 
   async getPackage() {
-    const pkg = await super.getPackage();
-    pkg.devDependencies.hyperapp = '*';
-    return pkg;
+    const pkg = await super.getPackage() || {};
+    const pack = pkg.devDependencies ? pkg : Object.assign(pkg, {
+      devDependencies: {
+        hyperapp: '*',
```
Comment (tripodsan) [inline src/parcel/AdapterJSAsset.js]: this is set twice now...

Comment (trieloff) [reply src/parcel/AdapterJSAsset.js]: Only when `devDependencies` didn't exist before.

Comment (tripodsan) [reply src/parcel/AdapterJSAsset.js]: why do you need it, btw ?

Comment (trieloff) [reply src/parcel/AdapterJSAsset.js]: In order to get `parcel` to think that the pragma for JSX files is `h` instead of `React.createElement` without forcing people to add it to their JSX files.

**Comment by kptdobe** [comment]
I do not see a newly added test that would prevent for this bug to happen again...
