### PR TITLE
fix #2354: Resources that redirect to protocol-relative URIs are not handled correctly

### LINKED ISSUE #2354: Resources that redirect to protocol-relative URIs are not handled correctly
**Description**

We are using the importer on a site that contains some redirects, which appear to be causing the `Crawl` to fail. An example URL:

```
$ curl -I https://www.hubblehomes.com/new-homes/idaho/boise-metro/nampa/franklin-village
HTTP/1.1 301 Moved Permanently
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Content-Type: text/html;charset=UTF-8
Location: //www.hubblehomes.com/new-homes/idaho/boise-metro/nampa/franklin-village-north
...
```

Note that the Location header does not specify the protocol.

This is handled incorrectly in HelixImportServer: https://github.com/adobe/helix-cli/blob/main/src/server/HelixImportServer.js#L127

.. where the conditonal code is skipped because the Location starts with `/`.

**To Reproduce**
1. Run the importer from this repo: `node ./index.js import --log-level silly`
4. In the workbench, enter `https://www.hubblehomes.com/new-homes/idaho/boise-metro/nampa/franklin-village`
5. In the Options, deselect "Save as docx"
6. Click Import button
7. Note the error:

Screenshot 2024-05-03 at 1 07 55 PM

**Expected behavior**
The redirect should be detected and an error should not be thrown. This error appears to be causing a Crawl of this site to fail. With a little fix in place (PR incoming):

Screenshot 2024-05-03 at 1 10 40 PM

**Version:**
run: `$ aem --version`

`16.3.11`

### PR DESCRIPTION
**Pull request by blefebvre**
## Related Issues

#2354

Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

### CODE REVIEW

File: src/server/HelixImportServer.js [hunk 1]
```diff
@@ -124,7 +124,11 @@ export class HelixImportServer extends BaseServer {
     respHeaders['access-control-allow-origin'] = '*';
     delete respHeaders['set-cookie'];
 
-    if (respHeaders.location && !respHeaders.location.startsWith('/')) {
+    if (respHeaders.location && (respHeaders.location.startsWith('http') || respHeaders.location.startsWith('//'))) {
+      if (respHeaders.location.startsWith('//')) {
+        const protocol = url.split('://')[0];
+        respHeaders.location = `${protocol}:${respHeaders.location}`;
+      }
```
Comment (tripodsan) [inline src/server/HelixImportServer.js:131]: I think this can be simplified, with:
```
const location = new URL(respHeaders.location, url);
```

**Review by tripodsan — CHANGES_REQUESTED** [review]
- simplify
- add test

**Comment by blefebvre** [comment]
Thanks @tripodsan for the feedback.

**Review by tripodsan — APPROVED** [review]
